WRIST = 0
THUMB_MCP = 2
THUMB_IP = 3
THUMB_TIP = 4
INDEX_FINGER_PIP = 6
INDEX_FINGER_DIP = 7
INDEX_FINGER_TIP = 8
MIDDLE_FINGER_PIP = 10
MIDDLE_FINGER_DIP = 11
MIDDLE_FINGER_TIP = 12
RING_FINGER_PIP = 14
RING_FINGER_DIP = 15
RING_FINGER_TIP = 16
PINKY_PIP = 18
PINKY_DIP = 19
PINKY_TIP = 20

FINGER_ANGLE_POINTS = {
    "THUMB": [WRIST, THUMB_MCP, THUMB_IP, THUMB_TIP],
    "INDEX": [WRIST, INDEX_FINGER_PIP, INDEX_FINGER_DIP, INDEX_FINGER_TIP],
    "MIDDLE": [WRIST, MIDDLE_FINGER_PIP, MIDDLE_FINGER_DIP, MIDDLE_FINGER_TIP],
    "RING": [WRIST, RING_FINGER_PIP, RING_FINGER_DIP, RING_FINGER_TIP],
    "PINKY": [WRIST, PINKY_PIP, PINKY_DIP, PINKY_TIP]
}
